telegram:
  # Put a custom token here or in your .env
  token: ${TELEGRAM_TOKEN}

llm:
  url: https://openrouter.ai/api/v1
  model: google/gemini-2.5-flash
  # Put a custom token here or in your .env
  token: ${OPENROUTER_TOKEN}

conversation:
  history: 5
