telegram:
  # Put a custom token here directly or a key in your .env
  token: ${TELEGRAM_TOKEN}

llm:
  # Change base URL and model name as necessary
  base_url: https://openrouter.ai/api/v1
  model: google/gemini-2.5-flash
  # Put a custom token here directly or a key in your .env
  api_key: ${OPENROUTER_TOKEN}

conversation:
  # How many messages to pass as context
  history: 5

# Custom prompts for different chatbot skills
prompts:
  system: |
    Your name is {name}. You are {description}.
    Reply in the user original language.

# This is the first message sent when the user hits /start
start:
  Hello {username}! I'm ready to answer your questions.
